/**
 * `serverRender`: the wiring an application would otherwise write by hand.
 *
 * The router, the query cache, server rendering and server functions are each
 * a deliverable and each works; none of them is a way to begin. This mode puts
 * them together — and it is opt-in, because the roadmap's own position is that
 * CSR is first-class and server rendering is something an application chooses,
 * never the price of using the framework. A turnkey mode that quietly made
 * every project a server project would contradict that, so `serverRender` is
 * `false` until somebody writes `true`.
 *
 * **The wiring is generated into the application's own module graph**, as
 * virtual modules, rather than shipped as a package the application depends
 * on. Three reasons, and the third is the one that decided it:
 *
 *   - `@voltdev/server` is deliberately dependency-free — a `(Request) =>
 *     Response` and nothing else — and giving it the router and the renderer
 *     would end that.
 *   - A sixth package is the opposite of what the section this comes from is
 *     called.
 *   - The generated code imports `@voltdev/core/server` and `@voltdev/router`
 *     by name, so the *application's* build resolves them, at the versions the
 *     application has. A package would have pinned its own.
 *
 * What the application supplies is a route table, a root component and the
 * `index.html` every Vite project has. What it does not supply is the request
 * handler, the mode dispatch, the state payload, the client bootstrap, or the
 * shell the handler writes into — which is the client build's own output, so
 * the page asks for the assets that build emitted.
 */

/** Where a route's markup is produced; the router's own type, restated. */
export type RenderMode = 'csr' | 'ssr' | 'ssg';

export interface ServerRenderOptions {
  /**
   * The module exporting `routes`, as the application would import it.
   *
   * A path and not a table, because the table is the application's and the two
   * halves below have to import it under the same specifier the application
   * does — one build, one module.
   */
  routes?: string;
  /**
   * The module exporting the root component as `default` or `App`.
   *
   * The component the router renders its outlet inside. Every page's markup
   * comes from here.
   */
  root?: string;
  /**
   * What a route that declares no mode of its own renders as.
   *
   * `ssr`, because an application that turned this on has said it wants a
   * server. A route says `csr` to opt back out, which is the direction that
   * keeps the roadmap's promise: server rendering is chosen, and choosing it
   * once for the application does not take the choice away per route.
   */
  defaultMode?: RenderMode;
  /** Where server-function calls arrive; must match the client transform. */
  base?: string;
  /**
   * The application's server entry, from the project root.
   *
   * What `vite build` builds into `server/` and what `vite` answers requests
   * with, so one module is both the deployable and the thing developed
   * against. It exports the handler the way a host expects one:
   *
   *     import { handler } from 'virtual:volt/server';
   *     export default { fetch: handler };
   */
  entry?: string;
}

/** The request handler, which the application's server entry exports. */
export const SERVER_ID = 'virtual:volt/server';
/** The browser bootstrap, which the application's client entry imports. */
export const CLIENT_ID = 'virtual:volt/client';
/**
 * The page the handler writes into, as a string.
 *
 * The client build's emitted `index.html` in a build — with the hashed module
 * script and the stylesheet link in it — and the project's own on a dev
 * server, where the source entry is what the dev server compiles on request.
 */
export const SHELL_ID = 'virtual:volt/shell';

/** Where in the shell the handler writes a page, spelled the one way it looks for. */
export const MOUNT_POINT = '<div id="app"></div>';

/**
 * The attribute a rendered mount point names its path in.
 *
 * Here rather than beside `BUILD_ATTRIBUTE` in core, because both ends of it
 * are generated by this module and nothing else reads it.
 */
const PATH_ATTRIBUTE = 'data-volt-path';

/**
 * Why the handler cannot write into this shell, naming `where`; null if it can.
 *
 * The client takes `#app` however the shell spells it, and the handler looks
 * for one spelling. A shell with another has nowhere for the render to go, and
 * a render written anywhere else is one the client never claims: it finds its
 * mount point empty and unmarked, builds the page into it, and the reader gets
 * two copies of the page, one of which never wakes. So the shell is refused
 * where it is loaded — failing the build, or the dev server's request — rather
 * than answered with that.
 */
export function missingMountPoint(shell: string, where: string): string | null {
  if (shell.includes(MOUNT_POINT)) return null;
  return (
    `[volt] ${where} has no ${MOUNT_POINT}. serverRender writes each page into that element, ` +
    'spelled exactly so — no attributes, nothing inside it — and the client attaches to what ' +
    'it finds there. Put one in the <body>, and style an element around it instead of it.'
  );
}

/** Every option decided, so the generated modules never default one twice. */
export interface ResolvedServerRender {
  readonly routes: string;
  readonly root: string;
  readonly defaultMode: RenderMode;
  readonly base: string;
  readonly entry: string;
}

/** `serverRender: true` and a partial object, as the one shape the rest reads. */
export function resolveServerRender(options: ServerRenderOptions | true): ResolvedServerRender {
  const given = options === true ? {} : options;
  return {
    routes: given.routes ?? '/src/routes.js',
    root: given.root ?? '/src/app.js',
    defaultMode: given.defaultMode ?? 'ssr',
    base: given.base ?? '/_volt/',
    entry: given.entry ?? '/server.ts',
  };
}

/** How the generated server module is being run. */
export interface ServerModuleOptions {
  /**
   * Under a dev server, where a failure should reach the overlay.
   *
   * A deployed handler answers a loader or a render that threw with a bare
   * 500, because what the error says — a driver's message, a stack — is not
   * for the stranger who asked. On a dev server the person who asked wrote
   * the code, and a 500 that says nothing sends them to the terminal to find
   * out which line it was. So there it is thrown, and the dev server shows it
   * in the page with the stack pointing at the source.
   */
  dev?: boolean;
}

/**
 * The server half: one `(Request) => Promise<Response>`.
 *
 * That shape is not decoration. The roadmap's edge mode "falls out of the
 * handler being a `(Request) => Response` function, provided nothing on the
 * render path reaches for a `node:` builtin" — which `renderPath` enforces
 * separately. Nothing here opens a file or reads a process.
 *
 * The order of the three branches is the whole logic. Server-function calls go
 * first, because they are POSTs to a path the router knows nothing about. A
 * URL the table does not match still gets the shell, with a 404 status: the
 * application's own not-found route is a route, and answering 200 for a URL
 * that does not exist would be worse than answering 404 with a page that says
 * so. And a `csr` route gets the shell unrendered, which is the opt-out.
 */
export function serverModule(
  options: ResolvedServerRender,
  build: string,
  { dev = false }: ServerModuleOptions = {},
): string {
  const failed = (error: string): string =>
    dev ? `throw ${error};` : `return new Response('Internal Server Error', { status: 500 });`;
  return `import { createRouter, flattenRoutes, matchRoutes, provideRouter, routeMode } from '@voltdev/router';
import { renderToString } from '@voltdev/core/server';
import { BUILD_ATTRIBUTE, needsHydration, provideOutlet } from '@voltdev/core';
import { createHandler, isServerCall, withRequest } from '@voltdev/server';
import shell from ${JSON.stringify(SHELL_ID)};
import { routes } from ${JSON.stringify(options.routes)};
import App from ${JSON.stringify(options.root)};

const branches = flattenRoutes(routes);
const functions = createHandler({ base: ${JSON.stringify(options.base)} });

const MARKER = ${JSON.stringify(MOUNT_POINT)};

/**
 * What this build calls itself.
 *
 * Written onto the mount point when the server rendered into it, and compared
 * by the client before it claims a single node — markup printed by another
 * build resolves every path and lands on the wrong nodes, which nothing on the
 * page can detect afterwards.
 */
const BUILD = ${JSON.stringify(build)};

/**
 * Where the mount point says which path it was rendered for.
 *
 * Beside the build's mark, because a host that rewrites a URL hands the
 * browser one route's markup at another route's address, and the client
 * resolves the address: its paths would land on the nodes of a page it is not.
 */
const PATH = ${JSON.stringify(PATH_ATTRIBUTE)};

/** The module script, and the only JavaScript the shell asks for. */
const SCRIPT = /<script\\b[^>]*\\btype=["']module["'][^>]*><\\/script>/;

/**
 * The shell either side of its mount point, cut once.
 *
 * Joined per request rather than spliced with \`replace\`, because a
 * replacement string is read for patterns — \`$$\` is one dollar and \`$'\` is
 * everything after the match — and what goes in here is whatever the render
 * wrote: a price, a formula, a stylesheet's \`content\`. The client claims the
 * static text as it arrives and never writes it again, and adopts the payload
 * as it arrives.
 */
function cut(page) {
  const at = page.indexOf(MARKER);
  return [page.slice(0, at), page.slice(at + MARKER.length)];
}

/**
 * With the module script and without it.
 *
 * Taken out of the shell rather than out of the finished page, where the first
 * match could as well be one the render printed.
 */
const LIVE = cut(shell);
const INERT = cut(shell.replace(SCRIPT, ''));

/**
 * Has this route anything at all to attach in a browser?
 *
 * Every component the URL matched is asked, because the outlet renders the
 * leaf's markup inside the layout's and either can have a binding in it. Each
 * component's answer already covers everything its own template reaches — a
 * child component is constructed by a runtime call, so a layout that renders
 * one is dynamic whatever its own markup looks like.
 *
 * A route with no components at all answers "yes". Unknown is not static.
 */
function interactive(matches) {
  // The root is asked with the rest of them. It renders on every page, and an
  // application whose only binding is in its own navigation would otherwise be
  // sent a page with nothing to attach it.
  const components = [App, ...matches.map((match) => match.route.component)].filter(Boolean);
  return components.length === 0 || components.some((component) => needsHydration(component));
}

function page(html, state, styles, status, script = true, path = '') {
  // Into the mount point rather than appended: the shell is the application's
  // own file and the mount point is where it says the application goes.
  // Declining to ship the JavaScript, which is the whole of partial hydration
  // once the boundary is known: a page of prose and links has nothing to
  // attach, so it asks for neither the bundle that would attach it nor the
  // values it would have attached.
  const [before, after] = script ? LIVE : INERT;
  // The state payload exists so hydration can start from what the server
  // settled on. A page that will not hydrate has nothing to read it, and on a
  // page of prose it can easily be the larger half.
  const carried = script ? state : '';
  // The mount point says which build filled it and for which path, and says
  // nothing when nothing did: a page the client must build for itself is a
  // page with no mark. A path keeps its \`&\` — nothing else in one needs
  // escaping in an attribute — and the parser hands the client it back.
  const opened = html
    ? '<div id="app" ' + BUILD_ATTRIBUTE + '="' + BUILD + '" ' + PATH + '="' +
      path.replaceAll('&', '&amp;') + '">'
    : '<div id="app">';
  // A function, so the stylesheets are not read for patterns either.
  const head = styles ? before.replace('</head>', () => styles + '</head>') : before;
  return new Response(head + opened + html + '</div>' + carried + after, {
    status,
    headers: { 'content-type': 'text/html; charset=utf-8' },
  });
}

export async function handler(request) {
  const url = new URL(request.url);

  // \`isServerCall\` rather than a prefix test: it requires a POST and compares
  // against the base with its trailing slash, so a page at \`/_voltage\` — or a
  // reader who typed a function URL into the address bar — is routed as a page
  // instead of being handed to the function handler and answered 405.
  if (isServerCall(request, ${JSON.stringify(options.base)})) return functions(request);

  // Every route that renders for this URL, outermost first — and an empty list,
  // not null, when nothing does. An empty array is truthy, so the test is on
  // its length.
  const matches = matchRoutes(branches, url.pathname);
  if (matches.length === 0) return page('', '', '', 404);

  const mode = routeMode(matches, ${JSON.stringify(options.defaultMode)});
  if (mode === 'csr') return page('', '', '', 200);

  // One router per request, and never one at module scope: a router there
  // would be shared by every request in flight, and the second reader would
  // see the first reader's page.
  const router = createRouter({ routes });

  // A server function called while this page is produced is a direct call on
  // the server, with no function handler to say whose request it is — so the
  // request is lent to each synchronous span of the work, and taken back
  // before every \`await\`, where another request's work runs next.
  const around = (run) => withRequest(request, run);

  // Wrapping \`resolve\` covers the loaders only because it calls every one of
  // them before it first awaits anything; the router's own tests hold it to
  // that. A loader is also how fetched data reaches the markup at all: its
  // answer is in place before the first byte is written, where a call made
  // during the render answers after the bytes it would have filled are gone.
  const resolved = await around(() => router.resolve(url));
  if (resolved.status === 'failed') {
    ${failed('resolved.error')}
  }
  // Everything a route reads is in place before a byte is written, and the
  // branch renders through the outlets in the application's own templates —
  // which is what makes this a page rather than a shell with a gap in it.
  const rendered = await renderToString(App, {
    around,
    setup: () => {
      provideRouter(router);
      provideOutlet(router.outletAt(0));
    },
  });
  if (rendered.status !== 200) {
    ${failed('rendered.error')}
  }
  const styles = [...rendered.styles.values()].map((css) => '<style>' + css + '</style>').join('');
  const answer = page(
    rendered.html,
    rendered.state ?? '',
    styles,
    200,
    interactive(matches),
    url.pathname,
  );
  // An \`ssr\` page is this reader's: every guard its loaders and functions ran
  // read this request, and a cache in front of the host keeps pages by URL,
  // so kept there it is the next reader's page too. \`private\` rather than the
  // \`no-store\` a server function's answer carries, because the reader's own
  // browser keeping it harms nobody and keeps Back instant. An \`ssg\` page is
  // the same for everyone by its own declaration, which is what makes it one a
  // shared cache should keep.
  if (mode === 'ssr') answer.headers.set('cache-control', 'private');
  return answer;
}

export { branches, routes };
`;
}

/**
 * The client half: take over the page the server sent, or build one.
 *
 * One entry for both, because the page cannot tell the browser which it is
 * receiving and should not have to. What decides is what the server said it
 * did, which it says with the identity of the build that did it.
 *
 * The order matters and is the same either way: resolve, then attach, then
 * listen. Resolving first puts every route's data and every depth's component
 * in place, so the render — whether it claims the server's nodes or builds its
 * own — is the render the page is meant to show. Listening last means the
 * first click cannot arrive before the page it would navigate from exists.
 */
export function clientModule(options: ResolvedServerRender, build: string): string {
  // Both entries whatever the default mode says. The default is only the
  // fallback: a route that declares `ssr` or `ssg` under a `csr` default is
  // rendered by the server all the same, and a client that could only mount
  // would throw every one of those pages away and build it again. Which
  // routes do that is the route table's business and is not known here, so
  // the hydration walk is in every client `serverRender` generates.
  return `import { BUILD_ATTRIBUTE, STATE_ATTRIBUTE, hydrate, mount, provideOutlet } from '@voltdev/core';
import { createRouter, provideRouter } from '@voltdev/router';
import { routes } from ${JSON.stringify(options.routes)};
import App from ${JSON.stringify(options.root)};

const host = document.querySelector('#app');
if (host) {
  // Decided by what the server said it did, which is the only thing that
  // knows: the mount point carries the identity of the build that filled it
  // and the path it filled it for, and nothing else on the page answers the
  // question. Children do not — a \`csr\` route's mount point is empty on a
  // server-rendered site, and a shell with a spinner in it is not. Markup
  // from another build, or rendered for another path than the one this
  // client resolves — a host that rewrites URLs — is markup whose paths would
  // resolve onto the wrong nodes: a claim compares only a root's tag.
  const claims =
    host.getAttribute(BUILD_ATTRIBUTE) === ${JSON.stringify(build)} &&
    host.getAttribute(${JSON.stringify(PATH_ATTRIBUTE)}) === location.pathname;
  // Building it again is right, and costs the reader a second paint of a page
  // they already had. Nobody chose that, so development says which half of
  // the deploy is out of step. A mount point with no mark is a \`csr\` page,
  // which was never the server's to print.
  if (__VOLT_DEV__ && !claims && host.hasAttribute(BUILD_ATTRIBUTE)) {
    const mark = host.getAttribute(BUILD_ATTRIBUTE);
    console.warn(
      mark === ${JSON.stringify(build)}
        ? '[volt] This page was rendered for ' + host.getAttribute(${JSON.stringify(PATH_ATTRIBUTE)}) +
            ' and opened at ' + location.pathname + ', so it is built again rather than claimed. ' +
            'Something between the server and the browser answered one path with the page for another.'
        : '[volt] This page was rendered by build ' + mark + ' and this client is build ' +
            ${JSON.stringify(build)} + ', so it is built again rather than claimed. ' +
            'A cache is serving a page from another deploy, or the server and the client were built apart.',
    );
  }
  // Values go with the markup they were printed with, before anything can
  // start from one. A payload's keys are names its authors chose, and the
  // build that wrote this page may have kept a name and changed what it
  // holds — which a component adopting it would show, and would not fetch
  // again.
  if (!claims) document.querySelector('script[' + STATE_ATTRIBUTE + ']')?.remove();

  const router = createRouter({ routes });
  const setup = () => {
    provideRouter(router);
    provideOutlet(router.outletAt(0));
  };

  // Before anything renders: a page claimed with an unresolved router would
  // claim a branch that is not there yet, and a page built with one would
  // build the shell and nothing under it. A resolve that fails still attaches:
  // the router says where the page is, and its outlets keep what the server
  // wrote there until a navigation replaces it.
  await router.resolve(location.href);

  // Two entries rather than a flag, because a flag would put the hydration
  // walk on \`mount\`'s own path where no bundler could drop it.
  if (claims) hydrate(App, host, { setup });
  else mount(App, host, { setup });

  // Listening, and not resolving again: the page the reader is looking at is
  // the page this router just resolved, and running every loader a second time
  // for it is work nobody asked for.
  await router.start({ resolve: false });
}
`;
}
